[tool.poetry]
name = "flame"
version = "0.1.0"
description = ""
authors = ["SunDoge <384813529@qq.com>"]

[tool.poetry.dependencies]
python = "^3.7"
rich = "^9.13.0"
jsonnet-binary = "^0.17.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.5.6"
ipdb = "^0.13.7"
Sphinx = "^3.5.2"
sphinx-autoapi = "^1.7.0"
pydata-sphinx-theme = "^0.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
