[tool.poetry]
name = "flame"
version = "0.1.0"
description = ""
authors = ["SunDoge <384813529@qq.com>"]

[tool.poetry.dependencies]
python = "^3.7"
rich = "^9.13.0"
jsonnet-binary = "^0.17.0"
injector = "^0.18.4"
tqdm = "^4.60.0"
typed-args = "0.5.1"
tabulate = "^0.8.9"
pydantic = "^1.8.1"
pfun = "^0.12.1"
pygtrie = "^2.4.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.5.6"
ipdb = "^0.13.7"
Sphinx = "^3.5.2"
sphinx-autoapi = "^1.7.0"
pydata-sphinx-theme = "^0.5.0"
flake8 = "^3.9.0"
torch = "^1.8.0"
icecream = "^2.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
testpaths = [
    "tests",
    # "integration",
]